# Publish the joint states to joint_states.
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 30.0

base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'left_wheel_joint'
  right_wheel : 'right_wheel_joint'
  publish_rate: 50.0               # default: 50
  #pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
  #twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]


  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.316
  wheel_radius : 0.3345 #the current value being used is the wheel radius * 3 | 0.223
  #EPH Configuring ROBOT PI gains from here (__u8)
  pid_gains:
      wheel_joint:
          p : 50
          i : 10

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0
  wheel_radius_multiplier    : 0.99
  
  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: base_footprint
  enable_odom_tf: false # true -> if not using ekf to publish tf
  publish_cmd: true

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.8  # m/s
      min_velocity           : -1.8 # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.2  # m/s^2
      min_acceleration       : -1.6 # m/s^2
      has_jerk_limits        : true
      max_jerk               : 8.5  # m/s^3
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 10.0  # rad/s
      min_velocity           : -10.0  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 7.5  # rad/s^2
      min_acceleration       : -7.5
      has_jerk_limits        : true
      max_jerk               : 22.5  # rad/s^3
