# hardware cmd vel topic: /base_controller/cmd_vel
topics:
- name    : keyboard
  topic   : keyboard/cmd_vel
  timeout : 0.3
  priority: 100
  
- name    : navigation
  topic   : follow_path/cmd_vel
  timeout : 0.5
  priority: 10
  
locks:
- name    : operator_system
  topic   : operator_priority
  timeout : 0.0
  priority: 100
