# manualmode cmd vel topics: /keyboard/cmd_vel /web_joy/cmd_vel
topics:
- name    : keyboard
  topic   : keyboard/cmd_vel
  timeout : 0.3
  priority: 50

- name    : web_joy
  topic   : web_joy/cmd_vel
  timeout : 0.3
  priority: 50
  
locks:
- name    : operator_system
  topic   : manual_lock
  timeout : 0.0
  priority: 100
